# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zf3Lc06Zw3rfBo0AElk-ZXlDQXxMhHQf

# Fase 2: Análise de Regressão Linear Múltipla
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.mplot3d import Axes3D

# =========================================================
# FUNÇÕES
# =========================================================

def plotDados(b0, b1, xvetor, yvetor, correlacao):
    ordem = np.argsort(xvetor)
    x_ord = xvetor[ordem]

    regressao = []
    for x in x_ord:
        regressao.append(b0 + b1 * x)

    plt.scatter(xvetor, yvetor)
    plt.plot(x_ord, regressao)

    plt.title(f"Correlação = {round(correlacao, 4)}")
    plt.xlabel("X")
    plt.ylabel("Preço")

    plt.show()


def calculaMedia(vetor):
    return sum(vetor) / float(len(vetor))


def soma(vetorx, vetory, mediax, mediay):
    soma_total = 0
    for x, y in zip(vetorx, vetory):
        soma_total += (x - mediax) * (y - mediay)
    return soma_total


def calculaCorrelacao(vetorx, vetory, xmedia, ymedia, soma1):
    somax = 0
    somay = 0

    for x, y in zip(vetorx, vetory):
        somax += (x - xmedia) ** 2
        somay += (y - ymedia) ** 2

    raiz = math.sqrt(somax * somay)
    correlacao = soma1 / raiz

    return float(correlacao), somax


# =========================================================
# DADOS
# =========================================================

df = pd.read_csv('data.csv', header=None)
df.columns = ['tamanho', 'quartos', 'preco']

xtamanho = df['tamanho'].to_numpy()
xquartos = df['quartos'].to_numpy()
y = df['preco'].to_numpy()

# =========================================================
# ESTATÍSTICAS
# =========================================================

print("média do preco:", df['preco'].mean())

print("preço da menor casa:",
      df.loc[df['tamanho'].idxmin(), 'preco'])

print("quartos da casa mais cara:",
      df.loc[df['preco'].idxmax(), 'quartos'])

# =========================================================
# REGRESSÃO MÚLTIPLA
# =========================================================

X = np.c_[np.ones(len(xtamanho)), xtamanho, xquartos]

XT = X.T
b = np.linalg.inv(XT @ X) @ XT @ y
yresultado = X @ b

print("Coeficientes:", b)

# =========================================================
# CORRELAÇÃO
# =========================================================

mediay = calculaMedia(y)
mediaxTamanho = calculaMedia(xtamanho)
mediaxQuartos = calculaMedia(xquartos)

somaTamanho = soma(xtamanho, y, mediaxTamanho, mediay)
somaQuartos = soma(xquartos, y, mediaxQuartos, mediay)

correlacaoTamanho, somaxT = calculaCorrelacao(
    xtamanho, y, mediaxTamanho, mediay, somaTamanho)

correlacaoQuartos, somaxQ = calculaCorrelacao(
    xquartos, y, mediaxQuartos, mediay, somaQuartos)

print("Correlação (tamanho vs preço):", correlacaoTamanho)
print("Correlação (quartos vs preço):", correlacaoQuartos)

# =========================================================
# REGRESSÃO SIMPLES (PARA GRÁFICOS)
# =========================================================

b11 = somaTamanho / somaxT
b01 = mediay - b11 * mediaxTamanho

b12 = somaQuartos / somaxQ
b02 = mediay - b12 * mediaxQuartos

plotDados(b01, b11, xtamanho, y, correlacaoTamanho)
plotDados(b02, b12, xquartos, y, correlacaoQuartos)

# =========================================================
# GRÁFICO 3D (REGRESSÃO MÚLTIPLA)
# =========================================================

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(xtamanho, xquartos, y)

tamanho_grid, quartos_grid = np.meshgrid(
    np.linspace(xtamanho.min(), xtamanho.max(), 30),
    np.linspace(xquartos.min(), xquartos.max(), 30)
)

preco_grid = b[0] + b[1]*tamanho_grid + b[2]*quartos_grid
ax.plot_surface(tamanho_grid, quartos_grid, preco_grid, alpha=0.5)

ax.text2D(0.05, 0.95,
          f"y = {b[0]:.2f} + {b[1]:.2f}*tamanho + {b[2]:.2f}*quartos",
          transform=ax.transAxes)

ax.set_xlabel("Tamanho")
ax.set_ylabel("Quartos")
ax.set_zlabel("Preço")

plt.title("Regressão Linear Múltipla (3D)")
plt.show()

# =========================================================
# PREVISÃO
# =========================================================

tamanho = 1650
quartos = 1

preco_estimado = b[0] + b[1]*tamanho + b[2]*quartos

print("Preço estimado:", preco_estimado)

"""- Calcule o preço de uma casa que tem tamanho de 1650 e 3 quartos. O resultado deve ser igual a 293081. Aumente e diminua a quantidade de número de quartos. O que acontece? Por qual motivo?

 R:  + quartos = - preco, - quartos = + preço.
 - Nosso modelo aprendeu que tamanho e quantidade de quartos tem correlção, como o modelo já considera o tamanho da casa, ao manter o tamanho fixo, um maior número de quartos implica em menor espaço por quarto, o que pode reduzir o valor do imóvel

### i)        Compare seus resultados com a função de regressão linear múltipla do python. Para isso você irá precisar das bibliotecas numpy e scikit-learn.
"""

from sklearn.linear_model import LinearRegression

# ------------------ SCIKIT-LEARN ------------------

# X sem coluna de 1 (o sklearn já cuida do intercepto)
X_sklearn = df[['tamanho', 'quartos']].to_numpy()
y_sklearn = df['preco'].to_numpy()

modelo = LinearRegression()
modelo.fit(X_sklearn, y_sklearn)

# coeficientes
b0_sklearn = modelo.intercept_
b1_sklearn, b2_sklearn = modelo.coef_

print("\n--- COMPARAÇÃO ---")
print("Meu modelo:")
print(f"b0 = {b[0]}, b1 = {b[1]}, b2 = {b[2]}")

print("\nScikit-learn:")
print(f"b0 = {b0_sklearn}, b1 = {b1_sklearn}, b2 = {b2_sklearn}")